### PR TITLE
Spawn `HoverPopover`s using the `hover-link` API

### LINKED ISSUE #227: Feature Request: Use the `hover-link` API
### Feature Requested

Hi, thank you so much for this amazing plugin!

I'd like to request changing how this plugin triggers hover popovers.
The current approach is to hook `mouseover` event handlers for editing view and reading view separately:

https://github.com/PKM-er/Obsidian-Surfing/blob/6f85b76b3ce668231c363e190b1fc4b60e3ed5b4/src/surfingIndex.ts#L567

This approach has several downsides:

A. The user cannot choose whether to use the `ctrl`/`cmd` key to trigger a hover popover
B. Unlike the built-in page preview, a hover popover does not show up when the user hovers over a link without `ctrl` and then presses it afterward. The current implementation requires `ctrl` to be already pressed at the moment the `mouseover` event is fired.
C. The current approach requires repeating similar lines of code if we want to show hover popovers at places other than markdown views.

To fix these problems, I'd like to propose using the standard `hover-link` API to show hover popovers rather than implementing Surfing's own logic.

Specifically:

1. [Register a `HoverLinkSource`](https://docs.obsidian.md/Reference/TypeScript+API/Plugin/registerHoverLinkSource) so that the user can configure whether to use the `ctrl`/`cmd` key (problem A).
```ts
// in the plugin's onload method
this.registerHoverLinkSource("surfing", { defaultMod: true, display: "Surfing" });
```

2. Replace the existing `mouseover` handlers with the following:
```ts
// calls the `onHoverLink` method of the core Page Preview plugin
this.app.workspace.trigger("hover-link", {
    event, // MouseEvent
    source: "surfing",
    hoverParent: view.currentMode, // in the case of markdown views
    targetEl: anchorEl, // the link element
    linktext: url,
    sourcePath: ""
});
```

This will fix problem B.

3. Using [`monkey-around`](https://github.com/pjeby/monkey-around), patch the core Page Preview's `onLinkHover` method so that it [shows Surfing's hover popover](https://github.com/PKM-er/Obsidian-Surfing/blob/6f85b76b3ce668231c363e190b1fc4b60e3ed5b4/src/surfingIndex.ts#L586-L598) when `linktext` is an external link URL.

To avoid conflicts with Hover Editor, we need to use monkey-around 3.0.0 or higher and patch the page preview plugin instance rather than the prototype: see https://github.com/RyotaUshio/obsidian-pdf-plus/blob/b09f87020b7ec95633eec1055ebdf9afb527b25e/src/patchers/page-preview.ts#L13 and https://github.com/nothingislost/obsidian-hover-editor/issues/259.

By implementing the hover popover feature in this way, other plugins can also easily trigger hover popover previews of external links powered by Surfing (problem C).
For example, previewing external links in PDF files will be a wonderful feature to have, which I'd love to add to my plugin [PDF++](https://github.com/RyotaUshio/obsidian-pdf-plus), which [already supports hover popover preview of internal links](https://github.com/RyotaUshio/obsidian-pdf-plus/blob/5fc5f1e41dc32ba4890c4c7a61d3e3a814563c13/src/pdf-link-like.ts#L100) (i.e. a link to another location in the same PDF file).
If Surfing's hover preview is implemented in the way I described above, all I have to do will be just trigger the `hover-link` event with proper parameters. Then my plugin will be able to open the target URL in a pretty hover popover thanks to the amazing power of Surfing!

If you are positive, I can send a PR myself. Thank you for your consideration.

### Relevant Screenshot

_No response_

### Checklist

- [X] The feature would be useful to more users than just me.

### PR DESCRIPTION
**Pull request by RyotaUshio**
Resolves #227.

A few things have changed from the initial plan I described in the linked issue.

- I avoided registering a custom `HoverLinkSource`, and instead, I used `source: "editor"` in the editing view and `source: "preview"` in the reading view to allow users to use `cmd`/`ctrl` in the editing view and not to use it in the reading view.
- I believe that back in Obsidian 1.4.x, `hoverParent` was `markdownView.currentMode`. But it seems to have changed in the editing view.
  - In the editing view, it now seems to be `hoverParent === cm.state.field(editorInfoField) ( === markdownView)`:
       - `MarkdownView`: https://github.com/PKM-er/Obsidian-Surfing/assets/72342591/86e85a81-be1f-45a5-825c-719109295a4d
       - Canvas: https://github.com/PKM-er/Obsidian-Surfing/assets/72342591/8468a049-92f9-4956-868e-c9a3413ebb5b
  - In the reading view, the `hoverParent` is unchanged and it's still `markdownView.previewMode`.
     https://github.com/PKM-er/Obsidian-Surfing/assets/72342591/521579bc-1edd-4a10-9ae7-4667e2f86808

  So I reflected this change in the editing view. However, in the reading view, we don't have a direct access to the `view` instance so I've ended up with just using `ctx: MarkdownPostProcessorContext` as the `hoverParent`. It is not ideal but will not be a big deal.

It's working fine, but I have one problem to solve before this PR is merged.
Obsidian's bulit-in `onLinkHover` method has a `setTimeout(..., 100)`, in which the content of `HoverPopover` is loaded. So I added this `setTimeout` [here](https://github.com/RyotaUshio/Obsidian-Surfing/blob/7dcc878e9011e55fdcb1dfa12de6c8507a7f3912/src/surfingIndex.ts#L630), but it caused the web page content to be displayed only in the upper half of the popover like this:

image

If I comment out the `setTimeout`, it works fine, but now the popover shows up too quickly compared to Obsidian's built-in popovers for internal links:

https://github.com/PKM-er/Obsidian-Surfing/assets/72342591/0e1cd00d-4c22-4b58-9966-b10a7c0b9019

@Quorafind Do you have any suggestions about how to get `setTimeout` to work?

### CODE REVIEW

**Comment by Quorafind** [comment]
I try and found if we change the wait time in `hoverPopover = new HoverPopover(hoverParent, targetEl, 200);` from 100 to 200, then we can use setTimeout to make it appear slowly. By the way, we can even set wait time as 101, it resolves the problem too. @RyotaUshio

**Comment by RyotaUshio** [comment]
@Quorafind Hi, thank you for your help! It indeed works well.
By the way, is there any reason why I chose the wait time of 100ms? I'm asking because, in Obsidian's native `onLinkHover` method, the `waitTime` parameter is omitted, which results in the default value of 300ms.
If 300ms is fine, it would make more sense to set it to `300` here, too.

**Comment by Quorafind** [comment]
@RyotaUshio LGTM, you can change it here

**Comment by RyotaUshio** [comment]
Updated!

**Comment by Quorafind** [comment]
Nice job.

**Pull request merged**
